# Default settings
start-at-login = true
default-root-container-layout = 'accordion'
default-root-container-orientation = 'horizontal'
accordion-padding = 30

[key-mapping]
    preset = 'qwerty'

# Monitor assignments
[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'secondary'

# Commands to run after AeroSpace starts
after-startup-command = [
    'workspace 1',
    'layout accordion horizontal',  # Start with horizontal tiling
]

# Auto-place new windows in workspace 1
[[on-window-detected]]
if.workspace = '1'
run = 'move-node-to-workspace 1'

# Gaps configuration
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

# Key bindings
[mode.main.binding]
	# Quick way to reset workspace 1 layout if needed
	alt-shift-1 = [
		'workspace 1',
    		'flatten-workspace-tree',  # First reset everything
    		'layout tiles', # Set initial tiling layout
		'focus left',
		'resize width -400',
			]
	# Toggle between accordion and tiled layouts
	alt-a = 'layout accordion'
	alt-t = 'layout tiles horizontal'

	# Manage windows in accordions
	alt-shift-leftSquareBracket = ['join-with left', 'layout accordion']
	alt-shift-rightSquareBracket = ['join-with right', 'layout accordion']

	# Arrow Key Bindings
	alt-up = 'focus up'     # Alternative to alt + k
    	alt-down = 'focus down' # Alternative to alt + j
    	alt-left = 'focus left'
    	alt-right = 'focus right'
